---
- name: Provision <MODULE COMPONENT NAME> container image
  hosts: packer

  vars_files:
    # Control node configuration
    - "{{ playbook_dir }}/../../../ryo-control-node/configuration/configuration.yml"
    # Host configuration
    - "{{ playbook_dir }}/../../../ryo-host/configuration/configuration_{{ host_id }}.yml"
    # Module configuration
    - "{{ playbook_dir }}/../../configuration/configuration.yml"


  roles:
    - role: upgrade-container
    - role: install-iptables
    - role: install-consul
    - role: set-up-firewall
    - role: set-up-consul
    # FURTHER ROLES DEPEND ON THE PROJECT
    - role: install-TEMPLATE
    - role: set-up-TEMPLATE
